version: '2.4'

services:
  rapids-env:
    env_file: .env
    build:
      context: ./configs
      dockerfile: Dockerfile
      args:
        UNAME: ${UNAME}
        UID: ${UID}
        GID: ${GID}
        UPASSWD: ${UPASSWD}
        SSHPORT: ${SSHPORT}
    runtime: nvidia
    container_name: rapids-env
    privileged: true
    environment: 
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "${NBPORT}:8888"
      - "${SSHPORT}:22"
    volumes:
      - ~/workspace:/home/${UNAME}/workspace
      - /home/${USER}/.ssh:/home/${UNAME}/.ssh
      - /home/${USER}/.kaggle:/home/${UNAME}/.kaggle
    user: "${UID}:${GID}"
    entrypoint:  bash /home/${UNAME}/.local/bin/docker-entrypoint.sh ${UPASSWD}
    
    
